### ISSUE TITLE
The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.

### ISSUE THREAD

**Issue by shahzadthathal** [joselfonseca/lighthouse-graphql-passport-auth#12]
When I tried to login, getting error:
graphQL

```
mutation{
  login(data:{
    username: "user@app.com",
    password: "123456"
  }){
    access_token
    refresh_token
    expires_in
    token_type
  }
}```
Error

```
{
  "errors": [
    {
      "message": "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.",
      "extensions": {
        "guards": [],
        "category": "authentication"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "login"
      ],
      "trace": [
        {
          "file": "/var/www/html/other/test/myProject/vendor/joselfonseca/lighthouse-graphql-passport-auth/src/GraphQL/Mutations/Login.php",
          "line": 21,
          "call": "Joselfonseca\\LighthouseGraphQLPassport\\GraphQL\\Mutations\\BaseAuthResolver::makeRequest(array(5))"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/nuwave/lighthouse/src/Schema/Directives/FieldDirective.php",
          "line": 48,
          "call": "Joselfonseca\\LighthouseGraphQLPassport\\GraphQL\\Mutations\\Login::resolve(null, array(2), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/nuwave/lighthouse/src/Schema/Factories/FieldFactory.php",
          "line": 221,
          "call": "Nuwave\\Lighthouse\\Schema\\Directives\\FieldDirective::Nuwave\\Lighthouse\\Schema\\Directives\\{closure}(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 632,
          "call": "Nuwave\\Lighthouse\\Schema\\Factories\\FieldFactory::Nuwave\\Lighthouse\\Schema\\Factories\\{closure}(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 560,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveOrError(instance of GraphQL\\Type\\Definition\\FieldDefinition, instance of GraphQL\\Language\\AST\\FieldNode, instance of Closure, null, instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 478,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveField(GraphQLType: Mutation, null, instance of ArrayObject(1), array(1))"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 921,
          "call": "GraphQL\\Executor\\ReferenceExecutor::GraphQL\\Executor\\{closure}(array(0), 'login')"
        },
        {
          "call": "GraphQL\\Executor\\ReferenceExecutor::GraphQL\\Executor\\{closure}(array(0), 'login')"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 923,
          "function": "array_reduce(array(1), instance of Closure, array(0))"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 494,
          "call": "GraphQL\\Executor\\ReferenceExecutor::promiseReduce(array(1), instance of Closure, array(0))"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 256,
          "call": "GraphQL\\Executor\\ReferenceExecutor::executeFieldsSerially(GraphQLType: Mutation, null, array(0), instance of ArrayObject(1))"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 208,
          "call": "GraphQL\\Executor\\ReferenceExecutor::executeOperation(instance of GraphQL\\Language\\AST\\OperationDefinitionNode, null)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/webonyx/graphql-php/src/Executor/Executor.php",
          "line": 155,
          "call": "GraphQL\\Executor\\ReferenceExecutor::doExecute()"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/webonyx/graphql-php/src/GraphQL.php",
          "line": 165,
          "call": "GraphQL\\Executor\\Executor::promiseToExecute(instance of GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter, instance of GraphQL\\Type\\Schema, instance of GraphQL\\Language\\AST\\DocumentNode, null, instance of Nuwave\\Lighthouse\\Schema\\Context, array(0), null, null)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/webonyx/graphql-php/src/GraphQL.php",
          "line": 98,
          "call": "GraphQL\\GraphQL::promiseToExecute(instance of GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter, instance of GraphQL\\Type\\Schema, 'mutation {\n  login(data: {username: \"user@app.com\", password: \"123456\"}) {\n    access_token\n    refresh_token\n    expires_in\n    token_type\n  }\n}', null, instance of Nuwave\\Lighthouse\\Schema\\Context, array(0), null, null, array(29))"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/nuwave/lighthouse/src/GraphQL.php",
          "line": 191,
          "call": "GraphQL\\GraphQL::executeQuery(instance of GraphQL\\Type\\Schema, 'mutation {\n  login(data: {username: \"user@app.com\", password: \"123456\"}) {\n    access_token\n    refresh_token\n    expires_in\n    token_type\n  }\n}', null, instance of Nuwave\\Lighthouse\\Schema\\Context, array(0), null, null, array(29))"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/nuwave/lighthouse/src/GraphQL.php",
          "line": 130,
          "call": "Nuwave\\Lighthouse\\GraphQL::executeQuery('mutation {\n  login(data: {username: \"user@app.com\", password: \"123456\"}) {\n    access_token\n    refresh_token\n    expires_in\n    token_type\n  }\n}', instance of Nuwave\\Lighthouse\\Schema\\Context, array(0), null, null)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/nuwave/lighthouse/src/Support/Http/Controllers/GraphQLController.php",
          "line": 79,
          "call": "Nuwave\\Lighthouse\\GraphQL::executeRequest(instance of Nuwave\\Lighthouse\\Execution\\LighthouseRequest)"
        },
        {
          "call": "Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController::query(instance of Nuwave\\Lighthouse\\Execution\\LighthouseRequest)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
          "line": 54,
          "function": "call_user_func_array(array(2), array(1))"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
          "line": 45,
          "call": "Illuminate\\Routing\\Controller::callAction('query', array(1))"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
          "line": 219,
          "call": "Illuminate\\Routing\\ControllerDispatcher::dispatch(instance of Illuminate\\Routing\\Route, instance of Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController, 'query')"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
          "line": 176,
          "call": "Illuminate\\Routing\\Route::runController()"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 680,
          "call": "Illuminate\\Routing\\Route::run()"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 30,
          "call": "Illuminate\\Routing\\Router::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/nuwave/lighthouse/src/Support/Http/Middleware/AcceptJson.php",
          "line": 30,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 163,
          "call": "Nuwave\\Lighthouse\\Support\\Http\\Middleware\\AcceptJson::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 104,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 682,
          "call": "Illuminate\\Pipeline\\Pipeline::then(instance of Closure)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 657,
          "call": "Illuminate\\Routing\\Router::runRouteWithinStack(instance of Illuminate\\Routing\\Route, instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 623,
          "call": "Illuminate\\Routing\\Router::runRoute(instance of Illuminate\\Http\\Request, instance of Illuminate\\Routing\\Route)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 612,
          "call": "Illuminate\\Routing\\Router::dispatchToRoute(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
          "line": 176,
          "call": "Illuminate\\Routing\\Router::dispatch(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 30,
          "call": "Illuminate\\Foundation\\Http\\Kernel::Illuminate\\Foundation\\Http\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/fideloper/proxy/src/TrustProxies.php",
          "line": 57,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 163,
          "call": "Fideloper\\Proxy\\TrustProxies::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
          "line": 21,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 163,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
          "line": 21,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 163,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",
          "line": 27,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 163,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php",
          "line": 62,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 163,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 104,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
          "line": 151,
          "call": "Illuminate\\Pipeline\\Pipeline::then(instance of Closure)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
          "line": 116,
          "call": "Illuminate\\Foundation\\Http\\Kernel::sendRequestThroughRouter(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/public/index.php",
          "line": 55,
          "call": "Illuminate\\Foundation\\Http\\Kernel::handle(instance of Illuminate\\Http\\Request)"
        }
      ]
    }
  ]
}
```

**Comment by joselfonseca** [comment]
Have you added this env vars?

```PASSPORT_CLIENT_ID=
PASSPORT_CLIENT_SECRET=```

They are needed for the request to work. This should be a Password Client.

**Comment by shahzadthathal** [comment]
Yes I have added above two lines in .env but without any value.

**Comment by shahzadthathal** [comment]
I have run this command
```php artisan passport:install --force```
The outpout is
```
Encryption keys generated successfully.
Personal access client created successfully.
Client ID: 3
Client secret: rFVUMDUHqRIfgt2ugUWPu2Dm4GAlFCCycceFHWFh
Password grant client created successfully.
Client ID: 4
Client secret: JJ5gMTKQdYpVOSv0R7IdbWnqMtEwo3ZseFNJl1sp

```

Then I used Client ID 3 in above config variables.
```
PASSPORT_CLIENT_ID=3
PASSPORT_CLIENT_SECRET=rFVUMDUHqRIfgt2ugUWPu2Dm4GAlFCCycceFHWFh
```

Now Error is change in graphql-playground

```
{
  "errors": [
    {
      "message": "Client authentication failed",
      "extensions": {
        "guards": [],
        "category": "authentication"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "login"
      ],
      "trace": [
        {
          "file": "/var/www/html/other/test/myProject/vendor/joselfonseca/lighthouse-graphql-passport-auth/src/GraphQL/Mutations/Login.php",
          "line": 21,
          "call": "Joselfonseca\\LighthouseGraphQLPassport\\GraphQL\\Mutations\\BaseAuthResolver::makeRequest(array(5))"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/nuwave/lighthouse/src/Schema/Directives/FieldDirective.php",
          "line": 48,
          "call": "Joselfonseca\\LighthouseGraphQLPassport\\GraphQL\\Mutations\\Login::resolve(null, array(2), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/nuwave/lighthouse/src/Schema/Factories/FieldFactory.php",
          "line": 221,
          "call": "Nuwave\\Lighthouse\\Schema\\Directives\\FieldDirective::Nuwave\\Lighthouse\\Schema\\Directives\\{closure}(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 632,
          "call": "Nuwave\\Lighthouse\\Schema\\Factories\\FieldFactory::Nuwave\\Lighthouse\\Schema\\Factories\\{closure}(null, array(1), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 560,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveOrError(instance of GraphQL\\Type\\Definition\\FieldDefinition, instance of GraphQL\\Language\\AST\\FieldNode, instance of Closure, null, instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 478,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveField(GraphQLType: Mutation, null, instance of ArrayObject(1), array(1))"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 921,
          "call": "GraphQL\\Executor\\ReferenceExecutor::GraphQL\\Executor\\{closure}(array(0), 'login')"
        },
        {
          "call": "GraphQL\\Executor\\ReferenceExecutor::GraphQL\\Executor\\{closure}(array(0), 'login')"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 923,
          "function": "array_reduce(array(1), instance of Closure, array(0))"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 494,
          "call": "GraphQL\\Executor\\ReferenceExecutor::promiseReduce(array(1), instance of Closure, array(0))"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 256,
          "call": "GraphQL\\Executor\\ReferenceExecutor::executeFieldsSerially(GraphQLType: Mutation, null, array(0), instance of ArrayObject(1))"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 208,
          "call": "GraphQL\\Executor\\ReferenceExecutor::executeOperation(instance of GraphQL\\Language\\AST\\OperationDefinitionNode, null)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/webonyx/graphql-php/src/Executor/Executor.php",
          "line": 155,
          "call": "GraphQL\\Executor\\ReferenceExecutor::doExecute()"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/webonyx/graphql-php/src/GraphQL.php",
          "line": 165,
          "call": "GraphQL\\Executor\\Executor::promiseToExecute(instance of GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter, instance of GraphQL\\Type\\Schema, instance of GraphQL\\Language\\AST\\DocumentNode, null, instance of Nuwave\\Lighthouse\\Schema\\Context, array(0), null, null)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/webonyx/graphql-php/src/GraphQL.php",
          "line": 98,
          "call": "GraphQL\\GraphQL::promiseToExecute(instance of GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter, instance of GraphQL\\Type\\Schema, 'mutation {\n  login(data: {username: \"test123@app.com\", password: \"123456\"}) {\n    access_token\n    refresh_token\n  }\n}', null, instance of Nuwave\\Lighthouse\\Schema\\Context, array(0), null, null, array(29))"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/nuwave/lighthouse/src/GraphQL.php",
          "line": 191,
          "call": "GraphQL\\GraphQL::executeQuery(instance of GraphQL\\Type\\Schema, 'mutation {\n  login(data: {username: \"test123@app.com\", password: \"123456\"}) {\n    access_token\n    refresh_token\n  }\n}', null, instance of Nuwave\\Lighthouse\\Schema\\Context, array(0), null, null, array(29))"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/nuwave/lighthouse/src/GraphQL.php",
          "line": 130,
          "call": "Nuwave\\Lighthouse\\GraphQL::executeQuery('mutation {\n  login(data: {username: \"test123@app.com\", password: \"123456\"}) {\n    access_token\n    refresh_token\n  }\n}', instance of Nuwave\\Lighthouse\\Schema\\Context, array(0), null, null)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/nuwave/lighthouse/src/Support/Http/Controllers/GraphQLController.php",
          "line": 79,
          "call": "Nuwave\\Lighthouse\\GraphQL::executeRequest(instance of Nuwave\\Lighthouse\\Execution\\LighthouseRequest)"
        },
        {
          "call": "Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController::query(instance of Nuwave\\Lighthouse\\Execution\\LighthouseRequest)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
          "line": 54,
          "function": "call_user_func_array(array(2), array(1))"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
          "line": 45,
          "call": "Illuminate\\Routing\\Controller::callAction('query', array(1))"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
          "line": 219,
          "call": "Illuminate\\Routing\\ControllerDispatcher::dispatch(instance of Illuminate\\Routing\\Route, instance of Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController, 'query')"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
          "line": 176,
          "call": "Illuminate\\Routing\\Route::runController()"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 680,
          "call": "Illuminate\\Routing\\Route::run()"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 30,
          "call": "Illuminate\\Routing\\Router::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/nuwave/lighthouse/src/Support/Http/Middleware/AcceptJson.php",
          "line": 30,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 163,
          "call": "Nuwave\\Lighthouse\\Support\\Http\\Middleware\\AcceptJson::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 104,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 682,
          "call": "Illuminate\\Pipeline\\Pipeline::then(instance of Closure)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 657,
          "call": "Illuminate\\Routing\\Router::runRouteWithinStack(instance of Illuminate\\Routing\\Route, instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 623,
          "call": "Illuminate\\Routing\\Router::runRoute(instance of Illuminate\\Http\\Request, instance of Illuminate\\Routing\\Route)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 612,
          "call": "Illuminate\\Routing\\Router::dispatchToRoute(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
          "line": 176,
          "call": "Illuminate\\Routing\\Router::dispatch(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 30,
          "call": "Illuminate\\Foundation\\Http\\Kernel::Illuminate\\Foundation\\Http\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/fideloper/proxy/src/TrustProxies.php",
          "line": 57,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 163,
          "call": "Fideloper\\Proxy\\TrustProxies::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
          "line": 21,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 163,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
          "line": 21,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 163,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",
          "line": 27,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 163,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php",
          "line": 62,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 163,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
          "line": 53,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 104,
          "call": "Illuminate\\Routing\\Pipeline::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
          "line": 151,
          "call": "Illuminate\\Pipeline\\Pipeline::then(instance of Closure)"
        },
        {
          "file": "/var/www/html/other/test/myProject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
          "line": 116,
          "call": "Illuminate\\Foundation\\Http\\Kernel::sendRequestThroughRouter(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/var/www/html/other/test/myProject/public/index.php",
          "line": 55,
          "call": "Illuminate\\Foundation\\Http\\Kernel::handle(instance of Illuminate\\Http\\Request)"
        }
      ]
    }
  ]
}
```

**Comment by joselfonseca** [comment]
Yes, you should use client 4 which is the password grant client

```
Client ID: 4
Client secret: JJ5gMTKQdYpVOSv0R7IdbWnqMtEwo3ZseFNJl1sp
```

**Comment by shahzadthathal** [comment]
Thanks you issue resolved by updating value with password grant client.

**Comment by lucaslrf** [comment]
I'm having the same problem. Even setting the .env file with client_id and client_secret with password grant client.

The following message still appears:

"message": "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed."

I need help, please.

**Comment by joselfonseca** [comment]
@lucaslrf Can you upload or reference the repo where you have the issue, I think this is configuration that needs to be changed.

**Comment by lucaslrf** [comment]
Yes, I think the same thing. Here is the repository link: https://github.com/lucaslrf/api-graphql.git

**Comment by joselfonseca** [comment]
https://github.com/lucaslrf/api-graphql/blob/master/routes/graphql/schema.graphql#L50 there you need to add the @spread directive. 

Please see https://github.com/joselfonseca/lighthouse-graphql-passport-auth/blob/master/graphql/auth.graphql#L60

**Comment by lucaslrf** [comment]
Yes, it worked. Thank you! 
Why do you need to add the @SPREAD directive?

**Comment by joselfonseca** [comment]
So the data passed to the function is flatten down a single array and we don't have to worry about if your schema has the parameter as `data` or `input`

https://github.com/joselfonseca/lighthouse-graphql-passport-auth/blob/master/src/GraphQL/Mutations/Login.php#L20

**Comment by lucaslrf** [comment]
Yes, excellent. Thank you very much.

**Comment by kevinpallado** [comment]
I still experience this problem, both solution above I use.

This is my workspace info
"require": {
        "php": "^7.2",
        "doctrine/dbal": "^2.10",
        "fideloper/proxy": "^4.0",
        "joselfonseca/lighthouse-graphql-passport-auth": "^2.0",
        "laravel/framework": "^6.2",
        "laravel/passport": "^8.0",
        "laravel/tinker": "^2.0",
        "mll-lab/laravel-graphql-playground": "^2.0",
        "nuwave/lighthouse": "^4.7"
    },
